# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_img_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 350)
        Form.setMaximumSize(QtCore.QSize(520, 350))
        self.cam = QtWidgets.QLabel(Form)
        self.cam.setGeometry(QtCore.QRect(10, 10, 480, 270))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cam.sizePolicy().hasHeightForWidth())
        self.cam.setSizePolicy(sizePolicy)
        self.cam.setAlignment(QtCore.Qt.AlignCenter)
        self.cam.setObjectName("cam")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(370, 280, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setObjectName("pushButton_save")
        self.img_save = QtWidgets.QLabel(Form)
        self.img_save.setGeometry(QtCore.QRect(0, 310, 351, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_save.sizePolicy().hasHeightForWidth())
        self.img_save.setSizePolicy(sizePolicy)
        self.img_save.setAlignment(QtCore.Qt.AlignCenter)
        self.img_save.setObjectName("img_save")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(330, 280, 31, 21))
        self.toolButton.setObjectName("toolButton")
        self.img_save_2 = QtWidgets.QLabel(Form)
        self.img_save_2.setGeometry(QtCore.QRect(0, 280, 321, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_save_2.sizePolicy().hasHeightForWidth())
        self.img_save_2.setSizePolicy(sizePolicy)
        self.img_save_2.setAlignment(QtCore.Qt.AlignCenter)
        self.img_save_2.setObjectName("img_save_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "svae_img_window"))
        self.cam.setText(_translate("Form", "not_things"))
        self.pushButton_save.setText(_translate("Form", "svae_img"))
        self.img_save.setText(_translate("Form", "save_image_name :"))
        self.toolButton.setText(_translate("Form", "..."))
        self.img_save_2.setText(_translate("Form", "save_dir :"))
